config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("syssel.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Job management
    url(r'^jobs/', include("syssel.job.urls", namespace="job")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

syssel/application/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

syssel/job/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from haystack.views import SearchView
from haystack.query import SearchQuerySet

from syssel.application.views import apply_view, ApplicationListView, ApplicationDeleteView

from . import views

from syssel.job.forms import JobSearchForm

urlpatterns = [
    # URL pattern for the JobListView
    url(
        regex=r'^$',
        view=views.JobListView.as_view(),
        name='job_listing'
    ),

    # URL pattern for job search
    url(r'^search/$', SearchView(
        template='job/job_search.html',
        searchqueryset=SearchQuerySet().filter(),
        form_class=JobSearchForm
        ), name="job_search"),

    # URL pattern for the job_posting_view
    url(
        regex=r'^post/$',
        view=views.job_posting_view,
        name='job_posting'
    ),

    # URL pattern for the JobDetailView
    url(
        regex=r'^(?P<headline>[\w.@+-]+)/$',
        view=views.JobDetailView.as_view(),
        name='job_detail'
    ),

    # URL pattern for the JobUpdateView
    url(
        regex=r'^(?P<headline>[\w.@+-]+)/update/$',
        view=views.JobUpdateView.as_view(),
        name='job_update'
    ),

    # URL pattern for the JobDeleteView
    url(
        regex=r'^(?P<headline>[\w.@+-]+)/delete/$',
        view=views.JobDeleteView.as_view(),
        name='job_delete'
    ),

    # URL pattern for the UserListView
    url(
        regex=r'^(?P<headline>[\w.@+-]+)/apply/$',
        view=apply_view,
        name='apply'
    ),

    # URL pattern for the ApplicationsListView
    url(
        regex=r'^(?P<job>[\w.@+-]+)/applications/$',
        view=ApplicationListView.as_view(),
        name='application_listing'
    ),

    # URL pattern for the ApplicationsDeleteView
    url(
        regex=r'^(?P<job>[\w.@+-]+)/applications/delete/$',
        view=ApplicationDeleteView.as_view(),
        name='application_delete'
    ),
]

syssel/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from syssel.job.views import MyJobsListView
from syssel.application.views import MyApplicationsListView

from haystack.views import SearchView
from haystack.query import SearchQuerySet

from . import views

from syssel.users.forms import UserSearchForm

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL patter for search
    url(r'^search/$', SearchView(
        template='users/user_search.html',
        searchqueryset=SearchQuerySet().filter(),
        form_class=UserSearchForm
        ), name="user_search"),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

    # URL pattern for the MyJobsListView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/myjobs/$',
        view=MyJobsListView.as_view(),
        name='my_jobs'
    ),

    # URL pattern for the MyApplicationsListView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/myapplications/$',
        view=MyApplicationsListView.as_view(),
        name='my_applications'
    ),
]

syssel/application/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models

from syssel.users.models import User
from syssel.job.models import Job


class Application(models.Model):
    """
    Application model
    """
    applicant = models.ForeignKey(User)
    job_name = models.ForeignKey(Job)
    application_date = models.DateTimeField(auto_now_add=True)

syssel/job/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.core.urlresolvers import reverse
from django.db import models

from taggit.managers import TaggableManager

from syssel.users.models import User


class Job(models.Model):
    """
    Job model
    """
    pub_date = models.DateTimeField(auto_now_add=True)
    headline = models.CharField(max_length=255)
    content = models.TextField()
    created_by = models.ForeignKey(User)

    tags = TaggableManager()

    def __unicode__(self):
        return self.headline

    def get_absolute_url(self):
        return reverse('job_detail', kwargs={'headline': self.headline})

syssel/application/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import forms

from syssel.users.models import User
from syssel.job.models import Job
from .models import Application


class ApplicationForm(forms.ModelForm):
    """
    Form to create applications
    """
    applicant = forms.ModelChoiceField(queryset=User.objects.all(), required=False)
    job_name = forms.ModelChoiceField(queryset=Job.objects.all(), required=False)

    class Meta:
        """
        Setting form to use Application as model
        """
        model = Application
        fields = ["applicant", "job_name",]

syssel/job/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import forms

from haystack.forms import SearchForm

from .models import Job


class JobForm(forms.ModelForm):
    """
    Form to create job posts
    """
    class Meta:
        """
        Setting form to use Job as model
        """
        model = Job
        fields = ["headline", "content", "tags",]


class JobSearchForm(SearchForm):
    """
    Form to search for jobs
    """
    def search(self):
        """
        Overridden search method to set SQS
        :return:
        """
        sqs = super(JobSearchForm, self).search()

        if not self.is_valid():
            return self.no_query_found()
        return sqs

syssel/application/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.shortcuts import render_to_response, RequestContext
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import ListView, DeleteView

from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.db.models import Q

from braces.views import LoginRequiredMixin

from .forms import ApplicationForm
from .models import Application
from syssel.contrib.utils import is_student
from syssel.job.models import Job


@login_required()
@user_passes_test(is_student, redirect_field_name=None)
def apply_view(request, **kwargs):
    """
    View for creating application
    :param request: GET request
    :param kwargs:
    :return: Application form with redirect if valid
    """
    form = ApplicationForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.applicant = request.user
        job = Job.objects.filter(headline=kwargs['headline'])[0]
        instance.job_name = job
        instance.save()

        return HttpResponseRedirect(reverse('users:my_applications', kwargs={"username": request.user.username}))
    return render_to_response("application/application_form.html", {
        "form": form,
    }, context_instance=RequestContext(request))


class MyApplicationsListView(LoginRequiredMixin, ListView):
    """
    View for a list of applications created by user
    """
    model = Application
    template_name = "application/my_applications_list.html"
    slug_field = "headline"
    slug_url_kwarg = "headline"

    #@user_passes_test(is_student, redirect_field_name=None)
    def dispatch(self, *args, **kwargs):
        """
        Overridden dispatch method to apply decorator to CBV
        :param args:
        :param kwargs:
        :return: MyApplication view with decorator
        """
        return super(MyApplicationsListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        """
        Method to get relevant data
        :return: Applications created by user
        """
        return Application.objects.filter(applicant__username=self.request.user)


class ApplicationListView(LoginRequiredMixin, ListView):
    """
    View for list over applications made to users job posting
    """
    model = Application

    def get_context_data(self, **kwargs):
        context = super(ApplicationListView, self).get_context_data(**kwargs)
        context['headline'] = self.kwargs['job']
        return context

    def get_queryset(self):
        """
        Method to get relevant data
        :return: Applications for jobs that are created by user AND has headline
        matching keyword argument given in URL
        """
        return Application.objects.filter(
            Q(job_name__headline=self.kwargs['job']) & Q(job_name__created_by=self.request.user))


class ApplicationDeleteView(LoginRequiredMixin, DeleteView):
    """
    View for deleting an application
    """
    model = Application
    success_url = reverse_lazy('job:application_delete')
    success_message = "The application was deleted successfully"

    slug_field = "applicant"
    slug_url_kwarg = "applicant"

    def delete(self, request, *args, **kwargs):
        """
        Overridden delete method to allow success message
        :param request: GET request
        :param args:
        :param kwargs:
        :return: Deletes job and redirects to success_url
        """
        messages.success(self.request, self.success_message)
        return super(ApplicationDeleteView, self).delete(request, *args, **kwargs)

syssel/job/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.shortcuts import render_to_response, RequestContext, render
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import DetailView, ListView, DeleteView, UpdateView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test

from braces.views import LoginRequiredMixin
from haystack.generic_views import SearchView

from .forms import JobForm
from .models import Job

from syssel.contrib.utils import is_corporate, AuthorRequiredMixin


@login_required()
@user_passes_test(is_corporate, redirect_field_name=None)
def job_posting_view(request):
    """
    View for  posting jobs
    :param request: get request
    :return: job posting form
    """
    form = JobForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.created_by = request.user
        instance.save()
        form.save_m2m()

        return HttpResponseRedirect(reverse('users:my_jobs', kwargs={"username": request.user.username}))
    return render_to_response("job/job_posting.html", {
        "form": form,
    }, context_instance=RequestContext(request))


class JobDetailView(LoginRequiredMixin, DetailView):
    """
    View for a detailed view for each job post
    """
    model = Job
    slug_field = "headline"
    slug_url_kwarg = "headline"


class JobUpdateView(AuthorRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    View for updating a job posting
    """
    form_class = JobForm
    model = Job
    success_message = "%(headline)s was successfully updated"

    slug_field = "headline"
    slug_url_kwarg = "headline"

    def get_success_url(self):
        """
        Redirects to given URL if form is valid
        :return: URL with keyword argument for that URL
        """
        return reverse("job:job_detail", kwargs={'headline': self.object.headline})

    def get_success_message(self, cleaned_data):
        """
        Creates a message if update was successful
        :param cleaned_data: Data from form to be used in message
        :return: Message displayed at URL given by success_url
        """
        return self.success_message % dict(cleaned_data, headline=self.object.headline)


class JobListView(ListView):
    """
    View for a list of all posted jobs
    """
    model = Job
    slug_field = "headline"
    slug_url_kwarg = "headline"


class JobDeleteView(AuthorRequiredMixin, DeleteView):
    """
    View for deleting a job post
    """
    model = Job
    success_url = reverse_lazy('job:job_listing')
    success_message = "The job was deleted successfully"

    slug_field = "headline"
    slug_url_kwarg = "headline"

    def delete(self, request, *args, **kwargs):
        """
        Overridden delete method to allow success message
        :param request: GET request
        :param args:
        :param kwargs:
        :return: Deletes job and redirects to success_url
        """
        messages.success(self.request, self.success_message)
        return super(JobDeleteView, self).delete(request, *args, **kwargs)


class MyJobsListView(LoginRequiredMixin, ListView):
    """
    View for list of jobs created by user
    """
    model = Job
    template_name = "job/my_jobs_list.html"
    slug_field = "headline"
    slug_url_kwarg = "headline"

    def get_queryset(self):
        """
        Method to get relevant data from model
        :return: Job posts created by user
        """
        return Job.objects.filter(created_by__username=self.request.user)

syssel/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin

from braces.views import LoginRequiredMixin

from .forms import UserForm
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    """
    View for user details
    """
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    """
    View for redirecting users to their profile page
    """
    permanent = False

    def get_redirect_url(self):
        """
        Method to redirect user to their profile page
        :return: URL to user profile with username as keyword argument
        """
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    View for updating user information
    """
    form_class = UserForm
    model = User
    success_message = "Your profile was successfully updated"

    # send the user back to their own page after a successful update
    def get_success_url(self):
        """
        Method for redirecting user to given URL if form is valid
        :return:
        """
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        """
        Method to only get record for the user making the request
        :return: Record of user making the request
        """
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        """
        Overridden form_valid to set user.completed if form is valid
        :param form: UserForm
        :return: Saves data from form if valid
        """
        instance = form.save(commit=False)
        instance.completed = "completed"
        return super(UserUpdateView, self).form_valid(form)


class UserListView(LoginRequiredMixin, ListView):
    """
    View for list of users
    """
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

syssel/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">

            <h2>{{ object.username }}</h2>
            {% if object.name %}
            <p>{{ object.name }}</p>
            {% endif %}
        </div>
    </div>
    {% if object == request.user %}
    <!-- Action buttons -->
    <div class="row">
        <div class="col-sm-12 ">
            <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>
            <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
            {% if object.is_corporate %}
            {% if object.is_complete %}
            <a class="btn btn-primary" href="{% url 'job:job_posting' %}">Create Job</a>
            <a class="btn btn-primary" href="{% url 'users:my_jobs' request.user %}">My Jobs</a>
            {% else %}
            <p><strong>You need to complete your profile before you can begin posting jobs</strong></p>
            <a class="btn btn-warning" href="">Create Job</a>
            <a class="btn btn-warning" href="">My Jobs</a>
            {% endif %}
            {% endif %}
            {% if object.is_student %}
            {% if object.is_complete %}
            <a class="btn btn-primary" href="{% url 'users:my_applications' request.user %}">My Applications</a>
            {% else %}
            <p><strong>You need to complete your profile before you can apply for jobs</strong></p>
            <a class="btn btn-warning" href="">My Applications</a>
            {% endif %}
            {% endif %}
        </div>


    </div>
    <!-- End Action buttons -->
    {% endif %}


</div>
{% endblock content %}

syssel/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
    </form>

{% endblock %}

syssel/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block search %}
    <form class="navbar-form navbar-right" role="search" action="{% url 'users:user_search' %}" method="get">
        <div class="form-group">
             <input type="text" class="form-control" placeholder="Search" name="q">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
    </form>
{% endblock search %}

{% block content %}
<div class="container">

    <h2>Users</h2>

    <div class="list-group">
        {% for user in user_list %}
        <a href="{% url 'users:detail' user.username %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ user.username }}</h4>
        </a>
        {% endfor %}

    </div>
</div>

{% endblock content %}

syssel/templates/users/user_search.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>Search Users</h2>

    <form class="form-horizontal" method="get" action="../search">

            {{ form|crispy }}

                <div class="control-group">
                    <div class="controls">
                        <button type="submit" class="btn">Update</button>
                    </div>
                </div>


        {% if query %}
            <h3>Results</h3>

            {% for result in page.object_list %}
               <a href="{% url 'users:detail' result.object.username %}" class="list-group-item">
                    <h4 class="list-group-item-heading">{{ result.object.username }}</h4>
               </a>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}